// <auto-generated />
using System;
using Family_and_Spa_Wellness.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Family_and_Spa_Wellness.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802221256_AddNotificationPreferences")]
    partial class AddNotificationPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasRescheduled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.ProviderAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "Date")
                        .IsUnique();

                    b.ToTable("ProviderAvailability");
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.ProviderShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWorking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "DayOfWeek");

                    b.ToTable("ProviderShifts");
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Massage",
                            Description = "Targeted pressure on deeper layers of muscle and connective tissue to relieve chronic pain and tightness.",
                            DurationMinutes = 90,
                            IsActive = true,
                            Name = "Deep Tissue Massage",
                            Price = 165m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Massage",
                            Description = "A full-body relaxation massage using long, gliding strokes to ease tension and improve circulation. Our most-booked introductory massage.",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Swedish Massage",
                            Price = 120m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Body Treatments",
                            Description = "A detoxifying wrap infused with essential oils to nourish and soften the skin.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Aromatherapy Body Wrap",
                            Price = 95m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Body Treatments",
                            Description = "A gentle, all-over exfoliating polish that leaves skin smooth, soft, and radiant.",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Body Polish & Buff",
                            Price = 110m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Facial & Skincare",
                            Description = "Our customized, multi-step facial designed around your specific skin type and concerns.",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Signature Facial",
                            Price = 135m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Facial & Skincare",
                            Description = "A collagen-boosting treatment targeting fine lines and loss of elasticity.",
                            DurationMinutes = 75,
                            IsActive = true,
                            Name = "Anti-Aging Collagen Facial",
                            Price = 160m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Wellness",
                            Description = "A full-body relaxation journey with lavender.",
                            DurationMinutes = 120,
                            IsActive = false,
                            Name = "Lavender Relaxation Ritual",
                            Price = 180m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Wellness & Add-Ons",
                            Description = "Add a custom essential oil blend to any massage or body treatment.",
                            DurationMinutes = 15,
                            IsActive = true,
                            Name = "Aromatherapy Enhancement (Add-On)",
                            Price = 15m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Massage",
                            Description = "Heated basalt stones placed on key points to melt away tension and restore energy flow, paired with a full-body massage.",
                            DurationMinutes = 75,
                            IsActive = true,
                            Name = "Hot Stone Therapy",
                            Price = 150m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Massage",
                            Description = "Pressure-point therapy on the feet and hands to restore balance and overall wellbeing.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Reflexology",
                            Price = 85m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Massage",
                            Description = "A gentle, side-lying massage tailored to the needs of expecting mothers, easing pregnancy-related tension safely.",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Prenatal Massage",
                            Price = 130m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Massage",
                            Description = "Side-by-side Swedish massages in our private couples suite, complete with champagne.",
                            DurationMinutes = 90,
                            IsActive = true,
                            Name = "Couples Retreat",
                            Price = 280m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Body Treatments",
                            Description = "Mineral-rich volcanic mud draws out impurities and leaves skin glowing and refreshed.",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Volcanic Mud Wrap",
                            Price = 130m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Body Treatments",
                            Description = "A full-body exfoliation using mineral salts to remove dead skin and stimulate circulation.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Detox Salt Scrub",
                            Price = 90m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Facial & Skincare",
                            Description = "A quick refresh - cleanse, exfoliate, and hydrate for guests short on time.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Express Facial",
                            Price = 70m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Facial & Skincare",
                            Description = "A moisture-replenishing treatment for dry or dehydrated skin, leaving it soft and dewy.",
                            DurationMinutes = 50,
                            IsActive = true,
                            Name = "Hydrating Facial",
                            Price = 110m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Nail Care",
                            Description = "A nourishing manicure with a moisturizing soak, shaping, cuticle care, and polish.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Hydrating Manicure",
                            Price = 55m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Nail Care",
                            Description = "A long-lasting, chip-resistant gel polish manicure with full nail prep.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Gel Manicure",
                            Price = 65m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Nail Care",
                            Description = "A relaxing foot soak, exfoliation, nail shaping, and polish.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Classic Pedicure",
                            Price = 60m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Nail Care",
                            Description = "An extended pedicure with a warm paraffin treatment and calf massage.",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Deluxe Spa Pedicure",
                            Price = 85m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Wellness & Add-Ons",
                            Description = "Private access to our dry sauna to relax muscles and promote detoxification.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Sauna Session",
                            Price = 25m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Wellness & Add-Ons",
                            Description = "Private access to our steam room to open pores and ease respiratory tension.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Steam Room Access",
                            Price = 20m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Wellness & Add-Ons",
                            Description = "Add a soothing scalp and head massage to any service.",
                            DurationMinutes = 15,
                            IsActive = true,
                            Name = "Scalp & Head Massage (Add-On)",
                            Price = 20m
                        });
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.ServiceNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ClientId");

                    b.ToTable("ServiceNotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 105,
                            ClientId = 100,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoteText = "Severe allergy to lavender oil — avoid all lavender-based products.",
                            NoteType = "Allergy"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 105,
                            ClientId = 100,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoteText = "Prefers firm pressure and warm room temperature.",
                            NoteType = "Preference"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 106,
                            ClientId = 101,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoteText = "Mild sensitivity to fragrances; use unscented products.",
                            NoteType = "Allergy"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 107,
                            ClientId = 102,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoteText = "Recovering from shoulder injury — avoid deep pressure on right shoulder.",
                            NoteType = "General"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 106,
                            ClientId = 103,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoteText = "Likes the calming playlist and dim lighting.",
                            NoteType = "Preference"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 108,
                            ClientId = 104,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoteText = "Allergic to nuts — check all product ingredient lists.",
                            NoteType = "Allergy"
                        });
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalStatus = "Approved",
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ReviewText = "This was exactly what I needed after months of desk work. My shoulders finally feel loose again."
                        },
                        new
                        {
                            Id = 2,
                            ApprovalStatus = "Approved",
                            ClientId = 2,
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ReviewText = "My skin has never looked better. The esthetician really listened to what I wanted."
                        },
                        new
                        {
                            Id = 3,
                            ApprovalStatus = "Approved",
                            ClientId = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            ReviewText = "Such a relaxing experience from start to finish. I'll definitely be back."
                        });
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyByEmail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.mitchell@example.com",
                            FirstName = "Sarah",
                            LastName = "Mitchell",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0201",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.whitfield@example.com",
                            FirstName = "James",
                            LastName = "Whitfield",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0202",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya.anand@example.com",
                            FirstName = "Priya",
                            LastName = "Anand",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0203",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lena.fischer@example.com",
                            FirstName = "Lena",
                            LastName = "Fischer",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0301",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "robert.chen@example.com",
                            FirstName = "Robert",
                            LastName = "Chen",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0302",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "megan.delgado@example.com",
                            FirstName = "Megan",
                            LastName = "Delgado",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0303",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tobias.brandt@example.com",
                            FirstName = "Tobias",
                            LastName = "Brandt",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0304",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yuki.tanaka@example.com",
                            FirstName = "Yuki",
                            LastName = "Tanaka",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0305",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "devon.cole@example.com",
                            FirstName = "Devon",
                            LastName = "Cole",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0401",
                            Role = "Provider"
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya.raman@example.com",
                            FirstName = "Priya",
                            LastName = "Raman",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0402",
                            Role = "Provider"
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marcus.whitfield@example.com",
                            FirstName = "Marcus",
                            LastName = "Whitfield",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0403",
                            Role = "Provider"
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sofia.lindqvist@example.com",
                            FirstName = "Sofia",
                            LastName = "Lindqvist",
                            NotifyByEmail = true,
                            PasswordHash = "seed-no-login",
                            Phone = "555-0404",
                            Role = "Provider"
                        });
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.Appointment", b =>
                {
                    b.HasOne("Family_and_Spa_Wellness.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Family_and_Spa_Wellness.Models.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Family_and_Spa_Wellness.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Provider");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.ProviderAvailability", b =>
                {
                    b.HasOne("Family_and_Spa_Wellness.Models.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.ProviderShift", b =>
                {
                    b.HasOne("Family_and_Spa_Wellness.Models.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.ServiceNote", b =>
                {
                    b.HasOne("Family_and_Spa_Wellness.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Family_and_Spa_Wellness.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.Testimonial", b =>
                {
                    b.HasOne("Family_and_Spa_Wellness.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
