// <auto-generated />
using System;
using Family_and_Spa_Wellness.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Family_and_Spa_Wellness.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731061608_AddProviderAvailability")]
    partial class AddProviderAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.ProviderAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "Date")
                        .IsUnique();

                    b.ToTable("ProviderAvailability");
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Massage",
                            Description = "Targeted pressure to release deep muscle tension.",
                            DurationMinutes = 90,
                            Name = "Deep Tissue Massage",
                            Price = 145m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Massage",
                            Description = "A gentle, flowing massage to ease everyday stress.",
                            DurationMinutes = 60,
                            Name = "Swedish Relaxation Massage",
                            Price = 110m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Body",
                            Description = "Nourishing botanical wrap with essential oils.",
                            DurationMinutes = 75,
                            Name = "Aromatherapy Body Wrap",
                            Price = 120m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Body",
                            Description = "A gentle, all-over exfoliating polish that leaves skin smooth, soft, and radiant.",
                            DurationMinutes = 50,
                            Name = "Body Polish & Buff",
                            Price = 100m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Facial & Skincare",
                            Description = "Customized facial for radiant, glowing skin.",
                            DurationMinutes = 60,
                            Name = "Signature Facial",
                            Price = 95m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Facial & Skincare",
                            Description = "A collagen-boosting treatment targeting fine lines and loss of elasticity.",
                            DurationMinutes = 60,
                            Name = "Anti-Aging Collagen Facial",
                            Price = 130m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Wellness",
                            Description = "A full-body relaxation journey with lavender.",
                            DurationMinutes = 120,
                            Name = "Lavender Relaxation Ritual",
                            Price = 180m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Wellness",
                            Description = "Add a custom essential oil blend to any massage or body treatment.",
                            DurationMinutes = 15,
                            Name = "Aromatherapy Enhancement",
                            Price = 25m
                        });
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalStatus = "Approved",
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ReviewText = "This was exactly what I needed after months of desk work. My shoulders finally feel loose again."
                        },
                        new
                        {
                            Id = 2,
                            ApprovalStatus = "Approved",
                            ClientId = 2,
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ReviewText = "My skin has never looked better. The esthetician really listened to what I wanted."
                        },
                        new
                        {
                            Id = 3,
                            ApprovalStatus = "Approved",
                            ClientId = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            ReviewText = "Such a relaxing experience from start to finish. I'll definitely be back."
                        });
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.mitchell@example.com",
                            FirstName = "Sarah",
                            LastName = "Mitchell",
                            PasswordHash = "seed-no-login",
                            Phone = "555-0201",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.whitfield@example.com",
                            FirstName = "James",
                            LastName = "Whitfield",
                            PasswordHash = "seed-no-login",
                            Phone = "555-0202",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya.anand@example.com",
                            FirstName = "Priya",
                            LastName = "Anand",
                            PasswordHash = "seed-no-login",
                            Phone = "555-0203",
                            Role = "Client"
                        });
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.Appointment", b =>
                {
                    b.HasOne("Family_and_Spa_Wellness.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Family_and_Spa_Wellness.Models.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Family_and_Spa_Wellness.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Provider");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.ProviderAvailability", b =>
                {
                    b.HasOne("Family_and_Spa_Wellness.Models.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.Testimonial", b =>
                {
                    b.HasOne("Family_and_Spa_Wellness.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
